// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-b1BIicqzs7OPSVN73ptMB_PeUXk_6E',
    appId: '1:55495130843:web:ff326c4f26a840805196fe',
    messagingSenderId: '55495130843',
    projectId: 'qanony-app',
    authDomain: 'qanony-app.firebaseapp.com',
    storageBucket: 'qanony-app.firebasestorage.app',
    measurementId: 'G-6CSR9S8NME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv48T6VwDasjGKzXbI2x3qX-rNWmusGIg',
    appId: '1:55495130843:android:9c0b32a86bdfdbec5196fe',
    messagingSenderId: '55495130843',
    projectId: 'qanony-app',
    storageBucket: 'qanony-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGJ3eMEM7dxCDzVXafBNepzpLjHP5JME',
    appId: '1:55495130843:ios:f893bb5ee595dae55196fe',
    messagingSenderId: '55495130843',
    projectId: 'qanony-app',
    storageBucket: 'qanony-app.firebasestorage.app',
    iosBundleId: 'com.example.qanony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGJ3eMEM7dxCDzVXafBNepzpLjHP5JME',
    appId: '1:55495130843:ios:f893bb5ee595dae55196fe',
    messagingSenderId: '55495130843',
    projectId: 'qanony-app',
    storageBucket: 'qanony-app.firebasestorage.app',
    iosBundleId: 'com.example.qanony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-b1BIicqzs7OPSVN73ptMB_PeUXk_6E',
    appId: '1:55495130843:web:0dfa857c31bca8a85196fe',
    messagingSenderId: '55495130843',
    projectId: 'qanony-app',
    authDomain: 'qanony-app.firebaseapp.com',
    storageBucket: 'qanony-app.firebasestorage.app',
    measurementId: 'G-91LSBNQ8ZV',
  );

}